spring.application.name=backend
server.port=${PORT:8080}


#bd supabase
#spring.datasource.url=jdbc:${DATABASE_URL}
#spring.datasource.username=${USER_BD}
#spring.datasource.password=${PASSWORD_BD}
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update   

spring.jpa.hibernate.ddl-auto=update
 spring.datasource.url=jdbc:postgresql://db.fsnmipdxmcwvqvyfjxmp.supabase.co:5432/postgres?sslmode=require
 spring.datasource.username=postgres
 spring.datasource.password=portafolio123#
 spring.datasource.driver-class-name=org.postgresql.Driver